In [2]:
import numpy as np

In [3]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
print(a.dtype)
print(a.shape)
print(a.size)
print(a.ndim)
print(a.flags) #?
print(a.strides) #?
print(a.data)
print(a.itemsize) #?
print(a.nbytes)
print(a.base) #?

int32
(2, 3)
6
2
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

(12, 4)
4
24
None


In [5]:
type(a)

numpy.ndarray

In [6]:
a[1]

array([4, 5, 6])

In [7]:
print(a)
print(a[0]) #getting the 1st row
print(a[1][0]) #getting the 1st element of the second row
print(a[1][:2]) #getting the 1st 2 elements of the second row
print(a[:,0]) #getting the 1st column
print(a[:,1]) #getting the 2nd column
print(a[:,2]) #getting the 3rd column

[[1 2 3]
 [4 5 6]]
[1 2 3]
4
[4 5]
[1 4]
[2 5]
[3 6]


In [8]:
#changing the a copy of the numpy array also changes the original array as they are pointing at the same array in the memory.
b = a[0]
b[1] = 10
print(b) 
print(a)

[ 1 10  3]
[[ 1 10  3]
 [ 4  5  6]]


In [12]:
#the transposedid not affect the original numpy array.
b = a.T
print(b)
print(a)
print(a.base)
print(b.base)
print(b.base is a)
a[0][0]=100
print(a)
print(b)


[[ 1  4]
 [10  5]
 [ 3  6]]
[[ 1 10  3]
 [ 4  5  6]]
None
[[ 1 10  3]
 [ 4  5  6]]
True
[[100  10   3]
 [  4   5   6]]
[[100   4]
 [ 10   5]
 [  3   6]]


In [10]:
print(a.real)
print(a.imag)

[[ 1 10  3]
 [ 4  5  6]]
[[0 0 0]
 [0 0 0]]
